### ISSUE TITLE
Error while running Allen connectivity datasets - QImage: :pixel: coordinate (X, Y) out of range

### ISSUE THREAD

**Issue by marovst** [leuat/nutil#87] opened 2020-01-30 08:50 UTC
When I run datasets downloaded from the allen institute database I get the following error:

QImage: :pixel: coordinate (X, Y) out of range
QImage: :setPixel: coordinate (X, Y) out of range

The datasets are anchored with QuickNII version 2017 and run with a custom region template.
See image of the error message and nutil file

![Nutil_QImagePixelError](https://user-images.githubusercontent.com/34418916/73433763-af3c7200-4345-11ea-9fdd-6e0da4edfe94.PNG)

[100140949_RSPv.txt](https://github.com/leuat/nutil/files/4133017/100140949_RSPv.txt)

**Comment by sharoncy** [comment] 2020-03-25 07:26
I just noticed this issue. In the future, please assign to leuat, sharoncy and majpuc in the top right corner) so that we get notified.  Has this been fixed @marovst or is this still an issue?

**Comment by Majpuc** [comment] 2020-05-15 08:02
Email with Marovst 15.05.20. The issue is fixed

**Closed by Majpuc** 2020-05-15 08:02 UTC
Labels: bug
